export const navData = [
  {
    id: "nav_home",
    title: "Home",
    url: "/",
    dropdown: false,
  },
  {
    id: "nav_about",
    title: "About Us",
    url: "/about-us",
    dropdown: false,
  },
  {
    id: "nav_blog",
    title: "Blog",
    url: "/blog",
    dropdown: false,
  },
  {
    id: "nav_blog_details",
    title: "Blog Details",
    url: "/blog-details",
    dropdown: false,
  },
  {
    id: "nav_loan",
    title: "Loan",
    url: "/loan",
    dropdown: true,
    dropdownItems: [
      {
        id: "loan_all",
        dropdown_title: "Loans",
        parentUrl: "/loan",
        sbu_dropdown: false,
        dropdownUrl: "/loan",
        sub_items: [],
      },
      {
        id: "loan_car",
        dropdown_title: "Car Loan",
        parentUrl: "/loan",
        sbu_dropdown: false,
        dropdownUrl: "/loan/car-loan",
        sub_items: [],
      },
      {
        id: "loan_education",
        dropdown_title: "Education Loan",
        parentUrl: "/loan",
        sbu_dropdown: false,
        dropdownUrl: "/loan/education-loan",
        sub_items: [],
      },
      {
        id: "loan_home",
        dropdown_title: "Home Loan",
        parentUrl: "/loan",
        dropdownUrl: "/loan/home-loan",
        sbu_dropdown: false,
        sub_items: [],
      },
      {
        id: "loan_personal",
        dropdown_title: "Personal Loan",
        parentUrl: "/loan",
        sbu_dropdown: false,
        dropdownUrl: "/loan/personal-loan",
        sub_items: [],
      },
    ],
  },
  {
    id: "nav_card",
    title: "Card",
    url: "/card",
    dropdown: true,
    dropdownItems: [
      {
        id: "card_credit",
        dropdown_title: "Credit Card",
        parentUrl: "/card",
        sbu_dropdown: false,
        dropdownUrl: "/card/credit-card",
        sub_items: [],
      },
      {
        id: "card_debit",
        dropdown_title: "Debit Card",
        parentUrl: "/card",
        sbu_dropdown: false,
        dropdownUrl: "/card/debit-card",
        sub_items: [],
      },
    ],
  },
  {
    id: "nav_service",
    title: "Service",
    url: "/service",
    dropdown: true,
    dropdownItems: [
      {
        id: "service_checking_service",
        dropdown_title: "Service",
        parentUrl: "/service",
        sbu_dropdown: false,
        dropdownUrl: "/service",
        sub_items: [],
      },
      {
        id: "service_checking",
        dropdown_title: "Checking Account",
        parentUrl: "/service",
        sbu_dropdown: false,
        dropdownUrl: "/service/checking-account",
        sub_items: [],
      },
    ],
  },
];
